language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

install: composer install

script: phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi'
